version: "3"

services:

  vsftpd:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - ./home:/home/vsftpd
      - ./logs:/var/log/vsftpd
